const {onRequest}=require("firebase-functions/v2/https");
const {setGlobalOptions}=require("firebase-functions/v2");
const admin=require("firebase-admin");
const express=require("express");
const cookieParser=require("cookie-parser");
const crypto=require("crypto");
const Razorpay=require("razorpay");

admin.initializeApp();
setGlobalOptions({region:"asia-south1",maxInstances:10});
const db=admin.firestore();
const app=express();
app.set("trust proxy",1);
app.use(express.json({limit:"1mb"}));
app.use(cookieParser());

const SESSION_MS=7*24*60*60*1000;
const hash=x=>crypto.createHash("sha256").update(x).digest("hex");
const token=()=>crypto.randomBytes(32).toString("base64url");
function passwordHash(p){const salt=crypto.randomBytes(16);const key=crypto.scryptSync(p,salt,64);return salt.toString("base64url")+"."+key.toString("base64url")}
function passwordOK(p,s){try{const [a,b]=s.split(".");const x=crypto.scryptSync(p,Buffer.from(a,"base64url"),64);const y=Buffer.from(b,"base64url");return x.length===y.length&&crypto.timingSafeEqual(x,y)}catch{return false}}
async function redis(command,args=[]){const r=await fetch(process.env.UPSTASH_REDIS_REST_URL,{method:"POST",headers:{Authorization:"Bearer "+process.env.UPSTASH_REDIS_REST_TOKEN,"Content-Type":"application/json"},body:JSON.stringify([command,...args])});if(!r.ok)throw Error("Redis unavailable");return(await r.json()).result}
async function limit(k,n,t){const c=await redis("INCR",[k]);if(Number(c)===1)await redis("EXPIRE",[k,t]);if(Number(c)>n){const e=Error("Too many requests");e.status=429;throw e}}
async function session(uid,role){const raw=token(),csrf=token();await db.doc("sessions/"+hash(raw)).set({userId:uid,role,csrfHash:hash(csrf),expiresAt:Date.now()+SESSION_MS,revoked:false});return{raw,csrf}}
async function current(req){const raw=req.cookies.ms_session;if(!raw)return null;const s=await db.doc("sessions/"+hash(raw)).get();if(!s.exists)return null;const d=s.data();if(d.revoked||d.expiresAt<Date.now())return null;const u=await db.doc("users/"+d.userId).get();if(!u.exists||u.data().status==="BLOCKED")return null;return{...d,id:s.id,user:u.data()}}
function setSession(res,s){res.cookie("ms_session",s.raw,{httpOnly:true,secure:true,sameSite:"lax",path:"/",maxAge:SESSION_MS});res.cookie("ms_csrf",s.csrf,{httpOnly:false,secure:true,sameSite:"lax",path:"/",maxAge:SESSION_MS})}
async function guard(req,res){const a=await current(req);if(!a){res.status(401).json({error:"Authentication required"});return null}return a}
function csrf(req,a){const t=req.get("x-csrf-token");return t&&hash(t)===a.csrfHash}
function email(x){return typeof x==="string"&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)&&x.length<255}
function pass(x){return typeof x==="string"&&x.length>=8&&x.length<=128&&/[a-z]/.test(x)&&/[A-Z]/.test(x)&&/[0-9]/.test(x)}

app.get("/api/health",(q,s)=>s.json({ok:true,service:"MS Tech EBook"}));
app.post("/api/auth/register",async(req,res)=>{try{const{name,email:rawEmail,password}=req.body||{};const e=String(rawEmail||"").trim().toLowerCase();await limit("reg:"+hash(e),5,3600);if(!name||!email(e)||!pass(password))return res.status(400).json({error:"Invalid account details"});const ref=db.doc("users/"+hash(e));if((await ref.get()).exists)return res.status(409).json({error:"Account already exists"});await ref.set({name:String(name).trim().slice(0,100),email:e,passwordHash:passwordHash(password),role:"user",status:"ACTIVE",createdAt:admin.firestore.FieldValue.serverTimestamp()});const s=await session(ref.id,"user");setSession(res,s);res.json({ok:true,user:{name:String(name).trim(),email:e},csrfToken:s.csrf})}catch(e){res.status(e.status||500).json({error:e.message})}});
app.post("/api/auth/login",async(req,res)=>{try{const{email:rawEmail,password}=req.body||{};const e=String(rawEmail||"").trim().toLowerCase();await limit("login:"+hash(e),10,900);const ref=db.doc("users/"+hash(e)),snap=await ref.get();if(!snap.exists||snap.data().status!=="ACTIVE"||!passwordOK(password,snap.data().passwordHash))return res.status(401).json({error:"Invalid email or password"});const s=await session(ref.id,snap.data().role||"user");setSession(res,s);res.json({ok:true,user:{name:snap.data().name,email:e,role:snap.data().role},csrfToken:s.csrf})}catch(e){res.status(e.status||500).json({error:e.message})}});
app.post("/api/auth/logout",async(req,res)=>{const a=await current(req);if(a)await db.doc("sessions/"+a.id).update({revoked:true});res.clearCookie("ms_session",{path:"/"});res.clearCookie("ms_csrf",{path:"/"});res.json({ok:true})});
app.get("/api/auth/me",async(req,res)=>{const a=await current(req);if(!a)return res.status(401).json({error:"Not logged in"});res.json({user:{name:a.user.name,email:a.user.email,role:a.role},csrfToken:req.cookies.ms_csrf||""})});

async function publicBook(d){const b={id:d.id,...d.data()};delete b.storagePath;delete b.coverPath;if(d.data().coverPath){try{const[url]=await admin.storage().bucket().file(d.data().coverPath).getSignedUrl({action:"read",expires:Date.now()+300000});b.coverUrl=url}catch{}}return b}
app.get("/api/books",async(req,res)=>{const s=await db.collection("books").where("status","==","ACTIVE").get();res.json({books:await Promise.all(s.docs.map(publicBook))})});
app.get("/api/books/:id",async(req,res)=>{const d=await db.doc("books/"+req.params.id).get();if(!d.exists||d.data().status!=="ACTIVE")return res.status(404).json({error:"Book not found"});res.json({book:await publicBook(d)})});

async function adminGuard(req,res){const a=await guard(req,res);if(!a)return null;if(a.role!=="admin")return res.status(403).json({error:"Admin access required"}),null;return a}
app.post("/api/admin/upload-url",async(req,res)=>{try{const a=await adminGuard(req,res);if(!a)return;if(!csrf(req,a))return res.status(403).json({error:"Invalid CSRF token"});const{name,type}=req.body||{};if(!name||!["application/pdf","image/jpeg","image/png","image/webp"].includes(type))return res.status(400).json({error:"Invalid file"});const ext=String(name).split(".").pop().toLowerCase();const folder=type==="application/pdf"?"ebooks":"covers";const path="private/"+folder+"/"+crypto.randomUUID()+"."+ext;const[url]=await admin.storage().bucket().file(path).getSignedUrl({version:"v4",action:"write",expires:Date.now()+15*60*1000,contentType:type});res.json({url,path})}catch(e){res.status(e.status||500).json({error:"Upload URL could not be created"})}});
app.post("/api/admin/books",async(req,res)=>{try{const a=await adminGuard(req,res);if(!a)return;if(!csrf(req,a))return res.status(403).json({error:"Invalid CSRF token"});const{title,author,category,description,type,price,coverPath,storagePath}=req.body||{};const free=type==="FREE";const p=free?0:Number(price);if(!title||!storagePath||!coverPath||!["FREE","PAID"].includes(type)||(type==="PAID"&&(!Number.isFinite(p)||p<=0)))return res.status(400).json({error:"Invalid book details"});const ref=db.collection("books").doc();await ref.set({title:String(title).trim().slice(0,200),author:String(author||"").trim().slice(0,120),category:String(category||"").trim().slice(0,80),description:String(description||"").trim().slice(0,5000),type,price:p,coverPath,storagePath,status:"ACTIVE",createdAt:admin.firestore.FieldValue.serverTimestamp(),createdBy:a.user.email});res.json({ok:true,id:ref.id})}catch(e){res.status(e.status||500).json({error:"Book could not be created"})}});
app.get("/api/admin/books",async(req,res)=>{try{const a=await adminGuard(req,res);if(!a)return;const s=await db.collection("books").orderBy("createdAt","desc").limit(100).get();res.json({books:s.docs.map(d=>({id:d.id,...d.data()}))})}catch(e){res.status(e.status||500).json({error:"Could not load admin books"})}});

app.post("/api/orders/create",async(req,res)=>{try{const a=await guard(req,res);if(!a)return;if(!csrf(req,a))return res.status(403).json({error:"Invalid CSRF token"});await limit("order:"+a.userId,5,60);const{bookId}=req.body||{};const b=await db.doc("books/"+bookId).get();if(!b.exists||b.data().status!=="ACTIVE")return res.status(404).json({error:"Book not found"});if(b.data().type==="FREE"||Number(b.data().price)<=0)return res.status(400).json({error:"This ebook is free. No payment is required"});const price=Number(b.data().price);const own=await db.doc("purchases/"+a.userId+"_"+bookId).get();if(own.exists&&own.data().status==="PAID")return res.status(409).json({error:"Already purchased"});const lock="order:"+a.userId+":"+bookId;if(await redis("SET",[lock,"1","NX","EX",30])===null)return res.status(409).json({error:"Order already in progress"});try{const rz=new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET});const o=await rz.orders.create({amount:Math.round(price*100),currency:"INR",receipt:("ebook_"+Date.now()).slice(0,40),notes:{userId:a.userId,bookId}});await db.doc("orders/"+o.id).set({userId:a.userId,bookId,amount:price,amountPaise:o.amount,status:"CREATED",createdAt:admin.firestore.FieldValue.serverTimestamp()});res.json({key:process.env.RAZORPAY_KEY_ID,order_id:o.id,amount:o.amount,currency:o.currency,name:"MS Tech EBook",description:b.data().title})}finally{await redis("DEL",[lock]).catch(()=>{})}}catch(e){res.status(e.status||500).json({error:e.message})}});
app.post("/api/orders/verify",async(req,res)=>{try{const a=await guard(req,res);if(!a)return;if(!csrf(req,a))return res.status(403).json({error:"Invalid CSRF token"});const{bookId,razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body||{};const o=await db.doc("orders/"+razorpay_order_id).get();if(!o.exists||o.data().userId!==a.userId||o.data().bookId!==bookId)return res.status(403).json({error:"Invalid order"});const expected=crypto.createHmac("sha256",process.env.RAZORPAY_KEY_SECRET).update(razorpay_order_id+"|"+razorpay_payment_id).digest("hex");if(expected!==razorpay_signature)return res.status(403).json({error:"Payment verification failed"});const rz=new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET});const p=await rz.payments.fetch(razorpay_payment_id);if(p.order_id!==razorpay_order_id||p.status!=="captured"||Number(p.amount)!==Number(o.data().amountPaise))return res.status(400).json({error:"Payment not captured or amount mismatch"});if(await redis("SET",["payment:"+razorpay_payment_id,a.userId,"NX","EX",86400])===null)return res.status(409).json({error:"Payment already processed"});await db.doc("purchases/"+a.userId+"_"+bookId).set({userId:a.userId,bookId,orderId:razorpay_order_id,paymentId:razorpay_payment_id,amount:o.data().amount,status:"PAID",purchasedAt:admin.firestore.FieldValue.serverTimestamp()});await o.ref.update({status:"PAID",paymentId:razorpay_payment_id});res.json({ok:true})}catch(e){res.status(e.status||500).json({error:e.message})}});
app.get("/api/library",async(req,res)=>{const a=await guard(req,res);if(!a)return;const s=await db.collection("purchases").where("userId","==",a.userId).where("status","==","PAID").get();const ids=new Set(s.docs.map(p=>p.data().bookId));const free=await db.collection("books").where("status","==","ACTIVE").where("type","==","FREE").get();free.docs.forEach(d=>ids.add(d.id));const books=[];for(const id of ids){const b=await db.doc("books/"+id).get();if(b.exists&&b.data().status==="ACTIVE")books.push(await publicBook(b))}res.json({books})});
app.get("/api/books/:id/secure-url",async(req,res)=>{try{const a=await guard(req,res);if(!a)return;await limit("read:"+a.userId,30,60);const b=await db.doc("books/"+req.params.id).get();if(!b.exists||b.data().status!=="ACTIVE")return res.status(404).json({error:"Ebook unavailable"});const free=b.data().type==="FREE"||Number(b.data().price)<=0;const p=await db.doc("purchases/"+a.userId+"_"+req.params.id).get();if(!free&&(!p.exists||p.data().status!=="PAID"))return res.status(403).json({error:"Purchase required"});if(!b.data().storagePath)return res.status(404).json({error:"Ebook unavailable"});const[url]=await admin.storage().bucket().file(b.data().storagePath).getSignedUrl({action:"read",expires:Date.now()+300000,responseDisposition:"inline"});res.json({url})}catch(e){res.status(e.status||500).json({error:e.message})}});

exports.api=onRequest({cors:false},app);